import openai
import shutil
import requests,turtle
from PIL import Image
import os
def uinput() -> dict:
    eye=input("Eye color? ").lower()
    hair=input("Hair color? ").lower()
    mouth=input("Mouth shape? ").lower()
    style=input("Hair style? ").lower()
    nose=input("Nose style? ").lower()
    tache=input("Moustache style? ").lower()
    general=input("Style? ").lower()
    to_ret={
        "eye":eye,
        "hair":hair,
        "mouth":mouth,
        "hairstyle":style,
        "nose":nose,
        "moustache":tache,
        "style":general
    }
    return to_ret
f = open("openai.api", "r")
key=f.readline()
f.close()
openai.api_key=key
f=True
while f:
    try:
        option=int(input("""
0 - Generated by DALL-E
1 - Written in Python turtle

"""))
        f=False
    except:
        f=True
if not option:
    eye=input("Eye color? ").lower()
    hair=input("Hair color? ").lower()
    mouth=input("Mouth shape? ").lower()
    style=input("Hair style? ").lower()
    nose=input("Nose style? ").lower()
    tache=input("Moustache style? ").lower()
    general=input("Style? ").lower()
    response = openai.Image.create(
    prompt=
    f"a face with {eye} eyes. big {hair}, {style} hair. a {mouth} mouth shape. a {nose} nose with a {tache} moustache. {general}",
    n=1,
    size="1024x1024"
    )
    image_url = response['data'][0]['url']
    response2 = requests.get(image_url, stream=True)
    with open('img.png', 'wb') as file:
        shutil.copyfileobj(response2.raw, file)
    del response2
    img = Image.open("img.png")
    img = img.convert("P")
    img.save("img.gif")

    win = turtle.Screen()
    win.bgpic('img.gif')
else:
    print("Turtle mode activated")
    metadata=uinput()